[package]
name = "helper"
version = "2.1.0-alpha.1"
authors = ["jmjoy <918734043@qq.com>"]
edition = "2018"
repository = "https://github.com/jmjoy/helper"
documentation = "https://docs.rs/helper/1.0.0/"
description = "A library provided some useful functions and macros for Rust."
license = "MulanPSL-2.0"

[dependencies]
